@startuml Domain Model

object "Product" as product {
    sku = "LC01-76-1038-1"
    name = "iPhone 12 / 12 Pro cover - Black"
    description = "A black iPhone 12 / 12 Pro cover"
    color = "Black"
    material = "Silicone / TPU"
    price = "17"
    
}

object "Category" as category {    
    name = "iPhone 12"  
    description = "A description text"
}

product -- category

@enduml
