services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5184:80"  # Maps host port 5184 to container port 80 for the API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KeyVaultUri=https://wepackkeys.vault.azure.net/
    networks:
      - pms-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5002:80"  # Maps host port 5002 to container port 80 for the Web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge