version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Team2Semester4"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LocalDB=Server=sqlserver;Database=WePackTest;User Id=sa;Password=Team2Semester4;TrustServerCertificate=true
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3001:8080"
    depends_on:
      - api

volumes:
  sqlserverdata: