@startuml Design Class Diagram (DCD)

package Core <<Folder>> {

    package Entities <<Folder>> {
        class User {
            + Id: string
            + UserName: string
            + Email: string
            + Password: string
            + Role: string        
        }

        ' REVIEW - Har tilføjet Currency og ændret navigation property til Arry<Category>
        class Product {
            + Id: int
            + Sku: string
            + Ean: string
            + Name: string
            + Description: string
            + Color: string
            + Material: string
            + ProductType: string
            + ProductGroup: string
            + Price: float
            + SpecialPrice: float     
            + Currency: string
            + Category: Array<Category>
        }

        class Category {
            + Id: int
            + Name: string
            + Description: string
            + BottomDescription : string
            + Products: Array<Product>
        }

        class Website {
            + Id: int
            + Domain: string
            + Currency: string
            + Language : string
        }

        class Platform {
            + Id: int
            + Name: string
        }

        ' class Localization {
        '     + Id: int
        '     + Language: string
        ' }
    }
}
package Application <<Folder>> {
    package Controllers <<Folder>> {
        class Controller
    }
}

Product "1..*" -- "1..*" Category
Product "0..*" -- "0..*" Website
' Website "0..1" -- "0..1" Localization
Website "0..*" -- "0..*" Platform



@enduml