@startuml
legend top left
    Use Case: Opret Produkt
    Bruger navigerer til opret produkt, indtaster data og trykker gem.
end legend

actor User
participant ":System" as System

User -> System: Naviger til Produkt side
User -> System: Indtast data
User -> System: Gem
System --> User: Valider data
System --> User: Bruger besked

@enduml
